In [1]:
import numpy as np    # pip install numpy
import pandas as pd   # pip install pandas

**Pandas** - Библиотек для работы с наборами дынных, таблицами и т.д. (CSV, Excel, SQL, ...)

In [2]:
# help(pd.Series)

In [3]:
my_index = ["Aziz", "Rasul", "Elvira", "Nadir", "Davut"]

In [4]:
my_data = [2008, 2006, 2007, 1980, 2006]

In [5]:
my_series = pd.Series(data=my_data, index=my_index)

In [6]:
my_series

Aziz      2008
Rasul     2006
Elvira    2007
Nadir     1980
Davut     2006
dtype: int64

In [7]:
my_series["Aziz"]

np.int64(2008)

In [8]:
ages = {"Aziz": 18, "Rasul": 20, "Elvira":19, "Nadir":45, "Davut":20}

In [9]:
pd.Series(ages)

Aziz      18
Rasul     20
Elvira    19
Nadir     45
Davut     20
dtype: int64

In [10]:
q1 = {"Narimanov":2000, "Xatai":2500, "Xachmaz":1200, "Xirdalan":1300}
q2 = {"20 yanvar":250,  "Xirdalan":1500, "Xatai":4500, "Quba":5200}

In [11]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [12]:
sales_q1

Narimanov    2000
Xatai        2500
Xachmaz      1200
Xirdalan     1300
dtype: int64

In [13]:
sales_q2

20 yanvar     250
Xirdalan     1500
Xatai        4500
Quba         5200
dtype: int64

In [14]:
sales_q1.keys()

Index(['Narimanov', 'Xatai', 'Xachmaz', 'Xirdalan'], dtype='str')

In [15]:
sales_q1.values

array([2000, 2500, 1200, 1300])

In [16]:
sales_q1 * 2

Narimanov    4000
Xatai        5000
Xachmaz      2400
Xirdalan     2600
dtype: int64

In [17]:
sales_q1 + sales_q2

20 yanvar       NaN
Narimanov       NaN
Quba            NaN
Xachmaz         NaN
Xatai        7000.0
Xirdalan     2800.0
dtype: float64

In [18]:
first_half = sales_q1.add(sales_q2, fill_value=0)

In [19]:
first_half

20 yanvar     250.0
Narimanov    2000.0
Quba         5200.0
Xachmaz      1200.0
Xatai        7000.0
Xirdalan     2800.0
dtype: float64

In [20]:
my_columns = ["Jan", "Feb", "Mar"]
np.random.seed(42)
my_index = ["Aziz", "Rasul", "Elvira", "Davut"]
my_data = np.random.randint(10, 99, (4, 3))
my_data

array([[61, 24, 81],
       [70, 30, 92],
       [96, 84, 84],
       [97, 33, 12]], dtype=int32)

In [21]:
df = pd.DataFrame(data=my_data, columns=my_columns, index=my_index)
df

        Jan  Feb  Mar
Aziz     61   24   81
Rasul    70   30   92
Elvira   96   84   84
Davut    97   33   12

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Aziz to Davut
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [23]:
employees = pd.read_csv("datas/employees.csv")
employees

     ID      Name   Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0         USA   30854               15    Yes         IT
1     2  Victoria  46.0  Azerbaijan   68623               11    Yes         HR
2     3  Benjamin  32.0     Germany   37392               18     No  Marketing
3     4      Luna   NaN         USA   85680               13     No    Finance
4     5       Zoe  38.0      Brazil   76717                5    Yes     Design
..  ...       ...   ...         ...     ...              ...    ...        ...
95   96   Abigail  59.0         USA   52399               16    Yes    Finance
96   97    Harper  56.0         USA   76214               18    Yes         IT
97   98      Owen  58.0      France  116416                4     No     Design
98   99     Ethan  45.0         USA  100271                8    Yes     Design
99  100   Grayson  24.0     Germany   74064               11    Yes         HR

[100 rows x 8 columns]

In [24]:
employees.columns

Index(['ID', 'Name', 'Age', 'Country', 'Salary', 'ExperienceYears', 'Remote',
       'Department'],
      dtype='str')

In [25]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               100 non-null    int64
 1   Name             100 non-null    str
 2   Age              97 non-null     float64
 3   Country          100 non-null    str
 4   Salary           100 non-null    int64
 5   ExperienceYears  100 non-null    int64
 6   Remote           100 non-null    str
 7   Department       100 non-null    str
dtypes: float64(1), int64(3), str(4)
memory usage: 6.4 KB

In [26]:
employees.head()

   ID      Name   Age     Country  Salary  ExperienceYears Remote Department
0   1      Lucy  56.0         USA   30854               15    Yes         IT
1   2  Victoria  46.0  Azerbaijan   68623               11    Yes         HR
2   3  Benjamin  32.0     Germany   37392               18     No  Marketing
3   4      Luna   NaN         USA   85680               13     No    Finance
4   5       Zoe  38.0      Brazil   76717                5    Yes     Design

In [27]:
employees.head(18)

    ID       Name   Age     Country  Salary  ExperienceYears Remote Department
0    1       Lucy  56.0         USA   30854               15    Yes         IT
1    2   Victoria  46.0  Azerbaijan   68623               11    Yes         HR
2    3   Benjamin  32.0     Germany   37392               18     No  Marketing
3    4       Luna   NaN         USA   85680               13     No    Finance
4    5        Zoe  38.0      Brazil   76717                5    Yes     Design
5    6  Sebastian  56.0       Japan  117092                5    Yes     Design
6    7    Paisley  36.0      France   80859               12     No    Finance
7    8      Jaxon  40.0  Azerbaijan   56309               18     No         HR
8    9      Aiden  28.0      Brazil  117455                7     No     Design
9   10      Wyatt  28.0      France   93734                1     No  Marketing
10  11      Logan  41.0      France  100467                0     No         HR
11  12      Riley  53.0         USA   82662               14    Yes  Marketing
12  13     Elijah   NaN      France   42688                0     No         IT
13  14       Emma  41.0       Japan   55342                4    Yes         HR
14  15      Jacob  20.0      Brazil   67157               15    Yes     Design
15  16      Grace  39.0      France   97863               18    Yes         HR
16  17   Scarlett  19.0         USA   82083                3     No         HR
17  18      Ellie  41.0       Japan   95733                2    Yes         HR

In [28]:
employees.tail()

     ID     Name   Age  Country  Salary  ExperienceYears Remote Department
95   96  Abigail  59.0      USA   52399               16    Yes    Finance
96   97   Harper  56.0      USA   76214               18    Yes         IT
97   98     Owen  58.0   France  116416                4     No     Design
98   99    Ethan  45.0      USA  100271                8    Yes     Design
99  100  Grayson  24.0  Germany   74064               11    Yes         HR

In [29]:
employees.tail(10)

     ID      Name   Age  Country  Salary  ExperienceYears Remote Department
90   91    Skylar  25.0   Brazil   68467               15     No         HR
91   92      John  52.0  Germany   53328               12    Yes    Finance
92   93    Samuel  52.0   France  116831               17    Yes         IT
93   94      Nora  50.0      USA   33987                9    Yes         HR
94   95  Penelope  22.0    Japan   88871               18    Yes         HR
95   96   Abigail  59.0      USA   52399               16    Yes    Finance
96   97    Harper  56.0      USA   76214               18    Yes         IT
97   98      Owen  58.0   France  116416                4     No     Design
98   99     Ethan  45.0      USA  100271                8    Yes     Design
99  100   Grayson  24.0  Germany   74064               11    Yes         HR

In [30]:
employees.sample()

    ID   Name   Age Country  Salary  ExperienceYears Remote Department
44  45  David  37.0   Japan   38155                7     No    Finance

In [31]:
employees.sample(7)

    ID      Name   Age     Country  Salary  ExperienceYears Remote Department
93  94      Nora  50.0         USA   33987                9    Yes         HR
15  16     Grace  39.0      France   97863               18    Yes         HR
30  31      Luke  32.0  Azerbaijan  102082               19    Yes     Design
17  18     Ellie  41.0       Japan   95733                2    Yes         HR
81  82    Sophia  42.0      Brazil  112018                6     No     Design
86  87  Savannah  25.0         USA  107505               14     No  Marketing
69  70   Jackson  40.0         USA   36295               16     No     Design

In [32]:
employees.describe()

               ID        Age        Salary  ExperienceYears
count  100.000000  97.000000     100.00000       100.000000
mean    50.500000  37.917526   72947.80000         9.560000
std     29.011492  12.163530   27241.56386         6.075817
min      1.000000  18.000000   30854.00000         0.000000
25%     25.750000  27.000000   49860.50000         4.000000
50%     50.500000  38.000000   73540.00000        10.000000
75%     75.250000  46.000000   95972.25000        15.000000
max    100.000000  59.000000  119045.00000        19.000000

In [33]:
employees["Age"].mean()

np.float64(37.91752577319588)

In [34]:
employees.Age.mean()

np.float64(37.91752577319588)

In [35]:
employees.Age.std()

np.float64(12.163529935059957)

In [36]:
employees[employees.Age > 50]

    ID       Name   Age     Country  Salary  ExperienceYears Remote Department
0    1       Lucy  56.0         USA   30854               15    Yes         IT
5    6  Sebastian  56.0       Japan  117092                5    Yes     Design
11  12      Riley  53.0         USA   82662               14    Yes  Marketing
19  20     Evelyn  55.0      Brazil   64698               16     No  Marketing
27  28     Thomas  59.0         USA   79811               13     No     Design
32  33    Eleanor  54.0       Japan   41411                2    Yes         IT
36  37       Leah  56.0  Azerbaijan   38680                7    Yes         IT
48  49       Noah  52.0      Brazil   51918               15     No  Marketing
51  52       Ezra  53.0  Azerbaijan   60306                2     No         IT
52  53      Dylan  57.0  Azerbaijan   46646               17    Yes    Finance
56  57    Lillian  59.0      France   32049               12    Yes  Marketing
61  62   Isabella  51.0         USA  102694               15     No         IT
63  64      James  53.0         USA   37400               11     No    Finance
70  71       Lily  57.0      France   89040               19    Yes     Design
77  78       Ryan  58.0      France   91267                7     No    Finance
91  92       John  52.0     Germany   53328               12    Yes    Finance
92  93     Samuel  52.0      France  116831               17    Yes         IT
95  96    Abigail  59.0         USA   52399               16    Yes    Finance
96  97     Harper  56.0         USA   76214               18    Yes         IT
97  98       Owen  58.0      France  116416                4     No     Design

In [37]:
employees.Age.value_counts()

Age
41.0    6
56.0    4
32.0    4
38.0    4
19.0    4
42.0    4
24.0    4
25.0    4
46.0    3
28.0    3
53.0    3
59.0    3
45.0    3
26.0    3
35.0    3
21.0    3
31.0    3
43.0    3
52.0    3
40.0    2
20.0    2
39.0    2
50.0    2
33.0    2
34.0    2
57.0    2
58.0    2
18.0    2
36.0    1
47.0    1
55.0    1
29.0    1
44.0    1
54.0    1
37.0    1
23.0    1
51.0    1
27.0    1
48.0    1
22.0    1
Name: count, dtype: int64

In [38]:
employees["Country"].value_counts()

Country
USA           22
Azerbaijan    18
France        18
Brazil        17
Japan         14
Germany       11
Name: count, dtype: int64

In [39]:
employees.groupby("Country")["Salary"].mean()

Country
Azerbaijan    72012.555556
Brazil        76001.882353
France        85016.111111
Germany       62115.000000
Japan         72384.214286
USA           67254.000000
Name: Salary, dtype: float64

In [40]:
employees.groupby("Country")["Age"].mean()

Country
Azerbaijan    37.277778
Brazil        34.470588
France        40.187500
Germany       36.727273
Japan         36.428571
USA           41.142857
Name: Age, dtype: float64

In [41]:
employees.index

RangeIndex(start=0, stop=100, step=1)

In [42]:
employees.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,100.0,50.500000,29.011492,1.0,25.75,50.5,75.25,100.0
Age,97.0,37.917526,12.163530,18.0,27.00,38.0,46.00,59.0
Salary,100.0,72947.800000,27241.563860,30854.0,49860.50,73540.0,95972.25,119045.0
ExperienceYears,100.0,9.560000,6.075817,0.0,4.00,10.0,15.00,19.0

In [43]:
employees[["Country", "Salary"]]

       Country  Salary
0          USA   30854
1   Azerbaijan   68623
2      Germany   37392
3          USA   85680
4       Brazil   76717
..         ...     ...
95         USA   52399
96         USA   76214
97      France  116416
98         USA  100271
99     Germany   74064

[100 rows x 2 columns]

In [44]:
employees.drop("Country", axis=1)

     ID      Name   Age  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0   30854               15    Yes         IT
1     2  Victoria  46.0   68623               11    Yes         HR
2     3  Benjamin  32.0   37392               18     No  Marketing
3     4      Luna   NaN   85680               13     No    Finance
4     5       Zoe  38.0   76717                5    Yes     Design
..  ...       ...   ...     ...              ...    ...        ...
95   96   Abigail  59.0   52399               16    Yes    Finance
96   97    Harper  56.0   76214               18    Yes         IT
97   98      Owen  58.0  116416                4     No     Design
98   99     Ethan  45.0  100271                8    Yes     Design
99  100   Grayson  24.0   74064               11    Yes         HR

[100 rows x 7 columns]

In [45]:
employees

     ID      Name   Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0         USA   30854               15    Yes         IT
1     2  Victoria  46.0  Azerbaijan   68623               11    Yes         HR
2     3  Benjamin  32.0     Germany   37392               18     No  Marketing
3     4      Luna   NaN         USA   85680               13     No    Finance
4     5       Zoe  38.0      Brazil   76717                5    Yes     Design
..  ...       ...   ...         ...     ...              ...    ...        ...
95   96   Abigail  59.0         USA   52399               16    Yes    Finance
96   97    Harper  56.0         USA   76214               18    Yes         IT
97   98      Owen  58.0      France  116416                4     No     Design
98   99     Ethan  45.0         USA  100271                8    Yes     Design
99  100   Grayson  24.0     Germany   74064               11    Yes         HR

[100 rows x 8 columns]

In [46]:
employees.drop("Country", axis=1, inplace=True)

In [47]:
employees

     ID      Name   Age  Salary  ExperienceYears Remote Department
0     1      Lucy  56.0   30854               15    Yes         IT
1     2  Victoria  46.0   68623               11    Yes         HR
2     3  Benjamin  32.0   37392               18     No  Marketing
3     4      Luna   NaN   85680               13     No    Finance
4     5       Zoe  38.0   76717                5    Yes     Design
..  ...       ...   ...     ...              ...    ...        ...
95   96   Abigail  59.0   52399               16    Yes    Finance
96   97    Harper  56.0   76214               18    Yes         IT
97   98      Owen  58.0  116416                4     No     Design
98   99     Ethan  45.0  100271                8    Yes     Design
99  100   Grayson  24.0   74064               11    Yes         HR

[100 rows x 7 columns]

In [48]:
employees.drop(0, axis=0)

     ID       Name   Age  Salary  ExperienceYears Remote Department
1     2   Victoria  46.0   68623               11    Yes         HR
2     3   Benjamin  32.0   37392               18     No  Marketing
3     4       Luna   NaN   85680               13     No    Finance
4     5        Zoe  38.0   76717                5    Yes     Design
5     6  Sebastian  56.0  117092                5    Yes     Design
..  ...        ...   ...     ...              ...    ...        ...
95   96    Abigail  59.0   52399               16    Yes    Finance
96   97     Harper  56.0   76214               18    Yes         IT
97   98       Owen  58.0  116416                4     No     Design
98   99      Ethan  45.0  100271                8    Yes     Design
99  100    Grayson  24.0   74064               11    Yes         HR

[99 rows x 7 columns]

In [49]:
employees.shape

(100, 7)

In [50]:
employees.set_index("Name", inplace=True)

In [51]:
employees

           ID   Age  Salary  ExperienceYears Remote Department
Name
Lucy        1  56.0   30854               15    Yes         IT
Victoria    2  46.0   68623               11    Yes         HR
Benjamin    3  32.0   37392               18     No  Marketing
Luna        4   NaN   85680               13     No    Finance
Zoe         5  38.0   76717                5    Yes     Design
...       ...   ...     ...              ...    ...        ...
Abigail    96  59.0   52399               16    Yes    Finance
Harper     97  56.0   76214               18    Yes         IT
Owen       98  58.0  116416                4     No     Design
Ethan      99  45.0  100271                8    Yes     Design
Grayson   100  24.0   74064               11    Yes         HR

[100 rows x 6 columns]

In [52]:
employees.loc["Zoe"]

ID                      5
Age                  38.0
Salary              76717
ExperienceYears         5
Remote                Yes
Department         Design
Name: Zoe, dtype: object

In [53]:
employees.iloc[4]

ID                      5
Age                  38.0
Salary              76717
ExperienceYears         5
Remote                Yes
Department         Design
Name: Zoe, dtype: object

In [54]:
employees.dtypes

ID                   int64
Age                float64
Salary               int64
ExperienceYears      int64
Remote                 str
Department             str
dtype: object

In [55]:
employees["Department"].str.lower()

Name
Lucy               it
Victoria           hr
Benjamin    marketing
Luna          finance
Zoe            design
              ...
Abigail       finance
Harper             it
Owen           design
Ethan          design
Grayson            hr
Name: Department, Length: 100, dtype: str

In [56]:
employees["Department"].str.contains("si")

Name
Lucy        False
Victoria    False
Benjamin    False
Luna        False
Zoe          True
            ...
Abigail     False
Harper      False
Owen         True
Ethan        True
Grayson     False
Name: Department, Length: 100, dtype: bool

In [57]:
employees[employees["Department"].str.contains("si")]

           ID   Age  Salary  ExperienceYears Remote Department
Name
Zoe         5  38.0   76717                5    Yes     Design
Sebastian   6  56.0  117092                5    Yes     Design
Aiden       9  28.0  117455                7     No     Design
Jacob      15  20.0   67157               15    Yes     Design
Violet     24  29.0   72107                2    Yes     Design
Anthony    26  42.0   81663                4    Yes     Design
Thomas     28  59.0   79811               13     No     Design
Luke       31  32.0  102082               19    Yes     Design
Mason      32  20.0   64754                0     No     Design
Bella      36  26.0  113763                2     No     Design
Charles    44  19.0   31802               16    Yes     Design
Gabriel    47  24.0   69384                8     No     Design
Julian     55  19.0   46371                6     No     Design
Hudson     61  43.0   91434               13    Yes     Design
Jackson    70  40.0   36295               16     No     Design
Lily       71  57.0   89040               19    Yes     Design
Christian  77  42.0   83351                0     No     Design
Michael    79  46.0   78354               11    Yes     Design
Ava        81  18.0   68360                4    Yes     Design
Sophia     82  42.0  112018                6     No     Design
Leo        86  18.0   51357               19     No     Design
Stella     88  41.0   32869                2     No     Design
Owen       98  58.0  116416                4     No     Design
Ethan      99  45.0  100271                8    Yes     Design

In [58]:
employees.Age += 1

In [59]:
employees

           ID   Age  Salary  ExperienceYears Remote Department
Name
Lucy        1  57.0   30854               15    Yes         IT
Victoria    2  47.0   68623               11    Yes         HR
Benjamin    3  33.0   37392               18     No  Marketing
Luna        4   NaN   85680               13     No    Finance
Zoe         5  39.0   76717                5    Yes     Design
...       ...   ...     ...              ...    ...        ...
Abigail    96  60.0   52399               16    Yes    Finance
Harper     97  57.0   76214               18    Yes         IT
Owen       98  59.0  116416                4     No     Design
Ethan      99  46.0  100271                8    Yes     Design
Grayson   100  25.0   74064               11    Yes         HR

[100 rows x 6 columns]

In [60]:
employees.rename(columns={"ExperienceYears":"Experience", "Salary":"Maaş"}, inplace=True)

In [61]:
employees

           ID   Age    Maaş  Experience Remote Department
Name
Lucy        1  57.0   30854          15    Yes         IT
Victoria    2  47.0   68623          11    Yes         HR
Benjamin    3  33.0   37392          18     No  Marketing
Luna        4   NaN   85680          13     No    Finance
Zoe         5  39.0   76717           5    Yes     Design
...       ...   ...     ...         ...    ...        ...
Abigail    96  60.0   52399          16    Yes    Finance
Harper     97  57.0   76214          18    Yes         IT
Owen       98  59.0  116416           4     No     Design
Ethan      99  46.0  100271           8    Yes     Design
Grayson   100  25.0   74064          11    Yes         HR

[100 rows x 6 columns]

In [62]:
employees.sort_values(by="Age")

          ID   Age    Maaş  Experience Remote Department
Name
Leo       86  19.0   51357          19     No     Design
Ava       81  19.0   68360           4    Yes     Design
Scarlett  17  20.0   82083           3     No         HR
Olivia    21  20.0  110623          11    Yes         IT
Julian    55  20.0   46371           6     No     Design
...       ..   ...     ...         ...    ...        ...
Thomas    28  60.0   79811          13     No     Design
Abigail   96  60.0   52399          16    Yes    Finance
Luna       4   NaN   85680          13     No    Finance
Elijah    13   NaN   42688           0     No         IT
Brooklyn  65   NaN   72642          18    Yes         IT

[100 rows x 6 columns]

In [63]:
employees.sort_values(by="Age", ascending=False)

          ID   Age    Maaş  Experience Remote Department
Name
Thomas    28  60.0   79811          13     No     Design
Abigail   96  60.0   52399          16    Yes    Finance
Lillian   57  60.0   32049          12    Yes  Marketing
Owen      98  59.0  116416           4     No     Design
Ryan      78  59.0   91267           7     No    Finance
...       ..   ...     ...         ...    ...        ...
Ava       81  19.0   68360           4    Yes     Design
Leo       86  19.0   51357          19     No     Design
Luna       4   NaN   85680          13     No    Finance
Elijah    13   NaN   42688           0     No         IT
Brooklyn  65   NaN   72642          18    Yes         IT

[100 rows x 6 columns]

In [64]:
employees.isna().sum()

ID            0
Age           3
Maaş          0
Experience    0
Remote        0
Department    0
dtype: int64

In [65]:
employees.dropna()
# employees.fillna(employees.Age.mean())

            ID   Age    Maaş  Experience Remote Department
Name
Lucy         1  57.0   30854          15    Yes         IT
Victoria     2  47.0   68623          11    Yes         HR
Benjamin     3  33.0   37392          18     No  Marketing
Zoe          5  39.0   76717           5    Yes     Design
Sebastian    6  57.0  117092           5    Yes     Design
...        ...   ...     ...         ...    ...        ...
Abigail     96  60.0   52399          16    Yes    Finance
Harper      97  57.0   76214          18    Yes         IT
Owen        98  59.0  116416           4     No     Design
Ethan       99  46.0  100271           8    Yes     Design
Grayson    100  25.0   74064          11    Yes         HR

[97 rows x 6 columns]

In [66]:
employees.Department.unique()

<StringArray>
['IT', 'HR', 'Marketing', 'Finance', 'Design']
Length: 5, dtype: str

In [67]:
employees.Department.nunique()

5

In [68]:
employees.reset_index(inplace=True)

In [69]:
employees

        Name   ID   Age    Maaş  Experience Remote Department
0       Lucy    1  57.0   30854          15    Yes         IT
1   Victoria    2  47.0   68623          11    Yes         HR
2   Benjamin    3  33.0   37392          18     No  Marketing
3       Luna    4   NaN   85680          13     No    Finance
4        Zoe    5  39.0   76717           5    Yes     Design
..       ...  ...   ...     ...         ...    ...        ...
95   Abigail   96  60.0   52399          16    Yes    Finance
96    Harper   97  57.0   76214          18    Yes         IT
97      Owen   98  59.0  116416           4     No     Design
98     Ethan   99  46.0  100271           8    Yes     Design
99   Grayson  100  25.0   74064          11    Yes         HR

[100 rows x 7 columns]